name: Magisk Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04 ]
    env:
      NDK_CCACHE: ccache
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      RUSTC_WRAPPER: sccache

    steps:

      - name: Check out
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Set up ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ runner.os }}-${{ github.sha }}
          restore-keys: ${{ runner.os }}

      - name: Set up sccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          variant: sccache
          key: ${{ runner.os }}-${{ github.sha }}
          restore-keys: ${{ runner.os }}

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            !~/.gradle/caches/build-cache-*
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Cache build cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches/build-cache-*
          key: ${{ runner.os }}-build-cache-${{ github.sha }}
          restore-keys: ${{ runner.os }}-build-cache-
      - name: Clone project
        run: |
          rm -rf ${{ github.workspace }}/*
          git clone --depth=1 https://github.com/topjohnwu/Magisk project
          cp -a project/. ${{ github.workspace }}

      - name: Clone external project
        run: |  
          cd ${{ github.workspace }}/native/src/external
          git clone https://github.com/topjohnwu/selinux.git selinux              
          git clone https://github.com/topjohnwu/ndk-busybox.git busybox
          git clone https://github.com/dgibson/dtc.git dtc
          git clone https://github.com/lz4/lz4.git lz4
          git clone https://github.com/nemequ/bzip2.git bzip2
          git clone https://github.com/xz-mirror/xz.git xz
          git clone https://github.com/nanopb/nanopb.git nanopb
          git clone https://github.com/topjohnwu/mincrypt.git mincrypt
          git clone https://android.googlesource.com/platform/external/pcre pcre
          git clone https://github.com/topjohnwu/libcxx.git libcxx
          git clone https://android.googlesource.com/platform/external/zlib zlib
          git clone https://github.com/greg7mdp/parallel-hashmap.git parallel-hashmap
          git clone https://github.com/google/zopfli.git zopfli
          git clone https://github.com/topjohnwu/cxx.git cxx-rs
          git clone https://github.com/LSPosed/LSPlt.git lsplt
        
          cd ${{ github.workspace }}/tools/termux-elf-cleaner
          git clone https://github.com/termux/termux-elf-cleaner.git termux-elf-cleaner
          cd ${{ github.workspace }}

      - name: Set up NDK
        run: python build.py -v ndk

      - name: Build release
        run: |
          python build.py -vr all

      # Only upload artifacts built on Linux
      - name: Upload build artifact
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.sha }}
          path: out
